# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{penso-feedbag}
  s.version = "0.6.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joel Duffin", "Justin Ball", "Fabien Penso"]
  s.date = %q{2009-11-10}
  s.description = %q{This gem will return title and url for each feed discovered at a given url, handling proper charset}
  s.email = %q{fabienpenso@gmail.com}
  s.extra_rdoc_files = [
    "ChangeLog",
     "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "COPYING",
     "ChangeLog",
     "README.markdown",
     "TODO",
     "VERSION",
     "benchmark/rfeedfinder_benchmark.rb",
     "feedbag.gemspec",
     "index.html",
     "lib/feedbag.rb",
     "rails/init.rb",
     "test/atom_autodiscovery_test.rb"
  ]
  s.homepage = %q{http://github.com/penso/muck-feedbag}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Fork of the feedbag gem.}
  s.test_files = [
    "test/atom_autodiscovery_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end
